### ISSUE TITLE
Feature request: Add support for python 3.8

### ISSUE THREAD

**Issue by imClumsyPanda** [nicedouble/StreamlitAntdComponents#10]
Thanks a lot for the gorgeous component! 

Is there any possibility to support python 3.8? That would help a lot!

**Comment by ShilpaGopal** [comment]
++

**Comment by imClumsyPanda** [comment]
I tried to change requirements in setup.py from ">=3.9" to ">=3.8" and installed with "python -m pip install . ", but it says "StreamlitAPIException: No such component directory:  '/xxx/envs/xxx/lib/python3.8/site-packages/streamlit_antd_components/frontend/build'".

**Comment by nicedouble** [comment]
@imClumsyPanda ,the latest version(0.1.9) now support py3.8.

**Comment by imClumsyPanda** [comment]
@nicedouble thanks a lot!
