### ISSUE TITLE
on_change argument for Menu widget

### ISSUE THREAD

**Issue by Puumanamana** [nicedouble/StreamlitAntdComponents#23]
Thank you for the work you're doing on this @nicedouble. 
I discovered the menu widget on `StreamlitAndComponents` and it seems to solve all of my issues... except one. I'd like to keep track of the entry the user selected, and add it in the URL. In regular streamlit, I usually do that using a callback (on_change, on_click) and calling `st.experimental_set_query_params()`. Since there is no `on_change` parameter for the menu, I can't. Is that something easy to implement?

**Comment by CHerSun** [comment]
I haven't worked with `st.experimental_set_query_params()`, but if the problem lies only in detecting the change itself something like this could help:
``` python
MENU_LAST_INDEX ="my_menu_last_index_key" 

index = menu(..., return_index=True)
if st.session_state.get(MENU_LAST_INDEX, None) != index:
    # index changed, do something
st.session_state[MENU_LAST_INDEX] = index
```

**Comment by Puumanamana** [comment]
I tried an approach like this. Unfortunately, the menu becomes very buggy when I do that. When I troubleshooted, it happens because of st.experimental_set_query_params() specifically (it updates the context, and it seems the apps refreshes). As a result, when I click on a menu item, it directly switches to another one.

**Comment by Puumanamana** [comment]
Here's a minimal example (following your recommendation):

```python
import streamlit as st
import streamlit_antd_components as sac

st.title("Issue #23")

key = "menu"

index = sac.menu(
    [sac.MenuItem('home'),
     sac.MenuItem('option 1'),
     sac.MenuItem('option 2'),],
    key=key,
    open_all=True,
    return_index=True,
)

if st.session_state.get(key, None) != index:
    st.experimental_set_query_params(**{key: index})
st.session_state[key] = index
```

Adding the menu index to the URL works here, but the menu selection doesn't work anymore (when I click on something, the highlighted MenuItem switches back to home.
I also setting `index=` to the session state or query params, but the behavior is off each time.

**Comment by CHerSun** [comment]
st.rerun won't help with context?

**Comment by Puumanamana** [comment]
It does work with that, didn't think of using the rerun. However, this makes the app really slow, and you can see the menu disappear and reappear each time you click.

**Comment by CHerSun** [comment]
Interesting. Sorry, I've never had to work with query params in streamlit, so don't know it's side effects.

Did some testing (was planning to use query params some time too), this is the closest I was able to make to what you want:
``` python
import streamlit as st
import streamlit_antd_components as sac

st.title("Issue #23")

previous_key = "menu_prev"


previous_index = st.session_state.get(previous_key, 0)
st.experimental_set_query_params(key=previous_index)


index = sac.menu(
    [sac.MenuItem('home'),
     sac.MenuItem('option 1'),
     sac.MenuItem('option 2'),],
     index=st.session_state.get(previous_key, 0),
#    key="menu",
    open_all=True,
    return_index=True,
    key="some_unique_key",
)

if previous_index != index:
    st.session_state[previous_key] = index
    st.rerun()

st.json(st.session_state)
```
It still blinks shortly, but at least works quite fast & reliable (both param and menu show the same item).

But there are a few observations on my side:
* `st.experimental_set_query_params(...)` works strangely right before `st.rerun`. It works more reliable at the very start of script. Callbacks should work nicely with it idd.
* there's no key in session_state with `menu(key='some_key')` at any stage at all.

I guess it's only @nicedouble who could help to further. Maybe adding on_change idd or some magic behind the scenes with session_state.

**Comment by CHerSun** [comment]
Looks like this https://github.com/streamlit/streamlit/issues/5954

**Comment by CHerSun** [comment]
oh, I recall now. I've seen this issue just recently. Here it is https://github.com/streamlit/streamlit/issues/7503 .
The problem is that custom components iframe gets fully reloaded due to change of URL. Setting parameters - you do change URL, so it's as if you do a full reload of the component anew.

**Comment by CHerSun** [comment]
And one more addition, judging by https://github.com/streamlit/streamlit/issues/3977 - custom components can't utilize callbacks in the current API state. Correct me if I'm wrong

**Comment by Puumanamana** [comment]
Thanks for all the links. That makes more sense.
I was actually trying out `options_menu` menu before, but it doesn't have hierarchical menus or tags attached to individual entries. I'm using options_menu in the meantime, but I'd like to come back to `StreamlitAntdComponents` eventually.

**Comment by Puumanamana** [comment]
I checked the solution implemented in streamlit #3977 you linked @CHerSun, and it seems most of it is already implemented in this package [here]( https://github.com/nicedouble/StreamlitAntdComponents/blob/master/streamlit_antd_components/utils/callback.py). 
If I understand correctly, we'd mostly missing a `on_change` argument in the `menu` widget and a call to `register_callback(key, on_change)`. I was unable to test it though, I'm not sure how to build the package release (some issues with `apache-arrow`.

**Comment by CHerSun** [comment]
@nicedouble thank you. Tested on_change today - looks good imo.

**Comment by Puumanamana** [comment]
It worked for me too, thank you @nicedouble
