### ISSUE TITLE
Translate reload button on "transfer" component

### ISSUE THREAD

**Issue by danilo-css** [nicedouble/StreamlitAntdComponents#28]
Is there a way to translate the hard coded names such as the "Reload" name in the "Transfer" component?

![image](https://github.com/nicedouble/StreamlitAntdComponents/assets/73763541/9847bd01-2a8a-4d0b-8393-3b6b54b88baf)

**Comment by nicedouble** [comment]
@danilo-css ，are you want to rename the 'Reload' to any string?

**Comment by danilo-css** [comment]
@nicedouble Yes! Is that possible?

By the way, thanks for the amazing package.

**Comment by nicedouble** [comment]
support in new version
