### ISSUE TITLE
Merge components into a single src folder

### ISSUE THREAD

**Issue by evertoncolling** [nicedouble/StreamlitAntdComponents#3]
I noticed there is one folder for each component, which is not scalable (if the idea is to support a wider selection of And-Design components) and increases the bundle size for development and consumption. There are already utility functions that are replicated on each component, so for the sake of maintainability, it would be better to merge all components into a single folder.

From this single folder, contributors can easily expand the library to add more Ant-Design components.

**Comment by evertoncolling** [comment]
I've spent some time looking into this, and even managed to make it work for the Menu and Tree. That being said, as a compromise we need to have only one method that is flexible enough to produce both components using clever argument handling. Even though it's possible, the end user experience is worse (in my opinion) and it will get worse as more components are added to the library.

**Comment by nicedouble** [comment]
Thanks for your reply, I also spent time on github looking up the file structure of other streamlit custom components before I created this component, but still couldn't solve the problem.

**Comment by nicedouble** [comment]
@evertoncolling ,I  find a way to put all components src files to a single src.
STEP 1: in every single componet, pass componet id and props to component_func.
STEP 2: in frontend index.tsx file,receive props in STEP1,and choose component to render base on component id.
Check out the source code structure for more details.

**Comment by evertoncolling** [comment]
I see what you did, really nice indeed! This will make it much easier to maintain and extend the library, good job!
