### ISSUE TITLE
Components are not displayed correctly in Streamlit v.1.29.0

### ISSUE THREAD

**Issue by SergeyPriem** [nicedouble/StreamlitAntdComponents#31]
In the newly released Streamlit v.1.29.0, Components are not displayed correctly: the text color and background color of elements become white (only the preset element is visible).
![image](https://github.com/nicedouble/StreamlitAntdComponents/assets/97326127/787c09e1-2fd1-41de-91f3-a1cb819c55a8)

**Comment by nicedouble** [comment]
thanks,fixed in new version.

**Comment by SergeyPriem** [comment]
Thank you for the good package and rapid fixing
