### ISSUE TITLE
[feature request] single button with use_container_width=True

### ISSUE THREAD

**Issue by boschmonart** [nicedouble/StreamlitAntdComponents#34]
Hi,
can i re-write a st.button in antd? preserving the width?

**native st**
```py
st.button(
'Delete scenario :wastebasket:', use_container_width=True)
```
**antd**
```py
sac.buttons([
            sac.ButtonsItem(
                label='Delete scenario', icon='trash')])
```

currently, width is not preserved
![image](https://github.com/nicedouble/StreamlitAntdComponents/assets/123999385/83a9d18f-4f86-4765-b689-82891fdee9a3)

**Comment by nicedouble** [comment]
hi，new version sac.buttons has `use_container_width `param.
