### ISSUE TITLE
Feature request: 3-way checkbox, like the one used in Tree

### ISSUE THREAD

**Issue by CHerSun** [nicedouble/StreamlitAntdComponents#6]
Streamlit only has 2-way checkbox - True or False.

But for some situations you do need 3-way checkbox - partial selections, filtering option (True - select what's True, False - select what's False, None - do not apply filtering).

I saw this component in Ant.Design. Would be great to add it too.

**Comment by nicedouble** [comment]
what component is that in Ant.Design?

**Comment by CHerSun** [comment]
https://ant.design/components/checkbox
with `indeterminate`
