### ISSUE TITLE
Feature request: Multi-line menu items

### ISSUE THREAD

**Issue by vktt** [nicedouble/StreamlitAntdComponents#7]
Currently, if the text of the menu items are too long, it get truncated. Would be great, if it could do a sort of word wrap and show big multi-line menu options. Attached is an example when using streamlit-option-menu:
<img width="364" alt="image" src="https://github.com/nicedouble/StreamlitAntdComponents/assets/2448637/6f16cabb-1285-4506-8405-5280cb60eb23">

**Comment by nicedouble** [comment]
The new version v0.1.5 support mulitple lines menu.
